export { categorize } from './array/categorize'
export { compact, truthy } from './array/truthy'
export { generateArray } from './array/generateArray'
export { split } from './array/split'
export { sum } from './array/sum'
export { tail } from './array/tail'
export { hasProp } from './object/hasProp'
export { objectFindKey } from './object/objectFindKey'
export { objectMap } from './object/objectMap'
